region: eu-west-1

project: qaz-project

stacks:
  vpc:
    # role: arn:aws:iam::121738883312:role/development-OpsLimitedAdmin-role
    source: |
              lambda:{
              	"stack": "vpc",
              	"cf": {
              		"cidr": "10.10.0.0/16"
              	}
              }@tropos_stacks
